var data = {
	body:[
		{
			width:48,
			height:122,
			path:'images/body/0.png'
		},{
			width:59,
			height:124,
			path:'images/body/1.png'
		},{
			width:54,
			height:122,
			path:'images/body/2.png'
		},{
			width:65,
			height:120,
			path:'images/body/3.png'
		},{
			width:52,
			height:109,
			path:'images/body/4.png'
		},{
			width:48,
			height:114,
			path:'images/body/5.png'
		},{
			width:76,
			height:131,
			path:'images/body/6.png'
		},{
			width:64,
			height:125,
			path:'images/body/7.png'
		},{
			width:66,
			height:124,
			path:'images/body/8.png'
		},{
			width:61,
			height:125,
			path:'images/body/9.png'
		},{
			width:53,
			height:128,
			path:'images/body/10.png'
		},{
			width:73,
			height:136,
			path:'images/body/11.png'
		},{
			width:71,
			height:122,
			path:'images/body/12.png'
		},{
			width:56,
			height:127,
			path:'images/body/13.png'
		},{
			width:65,
			height:125,
			path:'images/body/14.png'
		}
	],
	cheek:[
		{
			width:37,
			height:123,
			path:'images/cheek/0.png'
		},{
			width:54,
			height:133,
			path:'images/cheek/1.png'
		},{
			width:52,
			height:123,
			path:'images/cheek/2.png'
		},{
			width:40,
			height:124,
			path:'images/cheek/3.png'
		},{
			width:50,
			height:126,
			path:'images/cheek/4.png'
		},{
			width:56,
			height:123,
			path:'images/cheek/5.png'
		},{
			width:55,
			height:127,
			path:'images/cheek/6.png'
		},{
			width:131,
			height:165,
			path:'images/cheek/7.png'
		},{
			width:105,
			height:135,
			path:'images/cheek/8.png'
		},{
			width:136,
			height:145,
			path:'images/cheek/9.png'
		},{
			width:47,
			height:128,
			path:'images/cheek/10.png'
		},{
			width:101,
			height:102,
			path:'images/cheek/11.png'
		},{
			width:94,
			height:98,
			path:'images/cheek/12.png'
		},{
			width:83,
			height:118,
			path:'images/cheek/13.png'
		},{
			width:57,
			height:108,
			path:'images/cheek/14.png'
		},{
			width:56,
			height:126,
			path:'images/cheek/15.png'
		},{
			width:61,
			height:122,
			path:'images/cheek/16.png'
		},{
			width:40,
			height:129,
			path:'images/cheek/17.png'
		},{
			width:48,
			height:127,
			path:'images/cheek/18.png'
		},{
			width:61,
			height:124,
			path:'images/cheek/19.png'
		},{
			width:53,
			height:129,
			path:'images/cheek/20.png'
		}
	],
	children:[
		{
			width:58,
			height:135,
			path:'images/children/0.png'
		},{
			width:74,
			height:125,
			path:'images/children/1.png'
		},{
			width:103,
			height:124,
			path:'images/children/2.png'
		},{
			width:85,
			height:126,
			path:'images/children/3.png'
		},{
			width:73,
			height:126,
			path:'images/children/4.png'
		},{
			width:78,
			height:127,
			path:'images/children/5.png'
		},{
			width:126,
			height:83,
			path:'images/children/6.png'
		},{
			width:75,
			height:125,
			path:'images/children/7.png'
		}
	],
	healthcare:[
		{
			width:67,
			height:123,
			path:'images/children/0.png'
		},{
			width:56,
			height:128,
			path:'images/children/1.png'
		},{
			width:52,
			height:108,
			path:'images/children/2.png'
		}
	],
	label:[
		{
			width:128,
			height:21,
			path:'images/children/0.png'
		},{
			width:121,
			height:25,
			path:'images/children/1.png'
		},{
			width:123,
			height:24,
			path:'images/children/2.png'
		},{
			width:126,
			height:34,
			path:'images/children/3.png'
		},{
			width:125,
			height:51,
			path:'images/children/4.png'
		},{
			width:128,
			height:56,
			path:'images/children/5.png'
		},{
			width:129,
			height:50,
			path:'images/children/6.png'
		},{
			width:125,
			height:47,
			path:'images/children/7.png'
		},{
			width:124,
			height:44,
			path:'images/children/8.png'
		},{
			width:128,
			height:46,
			path:'images/children/9.png'
		},{
			width:129,
			height:47,
			path:'images/children/10.png'
		},{
			width:127,
			height:39,
			path:'images/children/11.png'
		}
	],
	thing:[
		{
			width:96,
			height:129,
			path:'images/children/0.png'
		},{
			width:119,
			height:118,
			path:'images/children/1.png'
		},{
			width:119,
			height:118,
			path:'images/children/2.png'
		},{
			width:69,
			height:125,
			path:'images/children/3.png'
		},{
			width:87,
			height:125,
			path:'images/children/4.png'
		},{
			width:98,
			height:126,
			path:'images/children/5.png'
		},{
			width:111,
			height:125,
			path:'images/children/6.png'
		},{
			width:96,
			height:128,
			path:'images/children/7.png'
		},{
			width:127,
			height:115,
			path:'images/children/8.png'
		},{
			width:96,
			height:126,
			path:'images/children/9.png'
		},{
			width:126,
			height:117,
			path:'images/children/10.png'
		},{
			width:127,
			height:106,
			path:'images/children/11.png'
		},{
			width:132,
			height:116,
			path:'images/children/12.png'
		},{
			width:124,
			height:69,
			path:'images/children/13.png'
		},{
			width:124,
			height:100,
			path:'images/children/14.png'
		},{
			width:62,
			height:126,
			path:'images/children/15.png'
		},{
			width:117,
			height:128,
			path:'images/children/16.png'
		},{
			width:157,
			height:105,
			path:'images/children/17.png'
		},{
			width:125,
			height:74,
			path:'images/children/18.png'
		},{
			width:126,
			height:60,
			path:'images/children/19.png'
		},{
			width:34,
			height:117,
			path:'images/children/20.png'
		},{
			width:110,
			height:120,
			path:'images/children/21.png'
		},{
			width:75,
			height:127,
			path:'images/children/22.png'
		},{
			width:73,
			height:125,
			path:'images/children/23.png'
		},{
			width:98,
			height:124,
			path:'images/children/24.png'
		}
	]
}